#!/bin/sh -e
export BHR_TEMPLATE=`pwd`/template.mako
./write_exa.py > inject.cfg
env BHR_TEMPLATE=`pwd`/template.mako exabgp.tcp.bind="0.0.0.0" exabgp.tcp.port=1790  ~/src/exabgp-3.4.3/sbin/exabgp inject.cfg
