#!/bin/sh
docker run -t -i --rm \
    -v `pwd`:/data \
    -e BHR_TEMPLATE=/data/template.mako \
    -e BHR_HOST=http://localhost:8000 \
    -e BHR_TOKEN=foo \
    -e BHR_IDENT=bgp1 \
    bhr-client-exabgp
